language: ruby
before_install:
  - gem install bundler -v '>= 1.5.1'
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
gemfile:
  - Gemfile
  - gemfiles/Gemfile-rails.3.2.x
notifications:
  email: false
  campfire:
    on_success: change
    on_failure: always
    rooms:
    - secure: "CDywaygYdWUAzxz08vXrUIOwRnuW/0B8A4VArgp+1z21fi1rWWCKrV6oqQW72Kbv4KkldkWLMMNBS7RY/aPehVWb/4xwQ91wF9vFTUljjn/fuwqN335ozHXFQOVWKCYVIukcRIbAsZvwgPbB/hBKIDasad+ucyangbWcvhBXreo="
